# Generated by Django 2.2.2 on 2019-08-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20190815_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Filters')),
            ],
        ),
    ]
