# Generated by Django 2.2.2 on 2019-08-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_filter_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='name',
            new_name='name_feature',
        ),
    ]
